logging:
  level:
    cn:
      licoy:
        wdog: debug
spring:
  datasource:
    url: jdbc:mysql://10.137.35.135:3306/oss?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      max-lifetime: 1765000
      maximum-pool-size: 15
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 10000
    pool:
      max-active: 10
      min-idle: 3
      max-idle: 5
    password: test123456
  aop:
    proxy-target-class: true
    auto: true
server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024
  port: 1000
